diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['Left_forward_joint', 'Left_backward_joint']
  right_wheel: ['Right_forward_joint', 'Right_backward_joint']
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
  publish_rate: 50
  wheel_separation: 0.5380
  wheel_radius: 0.1075
  cmd_vel_timeout: 0.25
  base_frame_id: base_link
  odom_frame_id: odom
  enable_odom_tf: true
